# Generated by Django 2.2.1 on 2020-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201106_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='real_price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
