# Generated by Django 2.2.1 on 2020-11-06 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201106_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('item1_image', models.ImageField(blank=True, upload_to='')),
                ('item2_image', models.ImageField(blank=True, upload_to='')),
                ('item3_image', models.ImageField(blank=True, upload_to='')),
                ('item4_image', models.ImageField(blank=True, upload_to='')),
                ('item5_image', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('price', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
